-- ═══════════════════════════════════════════════════════════════════════════════
-- SolarDistribution — Complete MariaDB schema
-- Generated by consolidating init + migrations v3, v4, v5, v6 and daily_summary
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS distribution_sessions (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    requested_at                DATETIME(6)     NOT NULL,
    surplus_w                   DECIMAL(10,3)   NOT NULL DEFAULT 0,
    total_allocated_w           DECIMAL(10,3)   NOT NULL DEFAULT 0,
    unused_surplus_w            DECIMAL(10,3)   NOT NULL DEFAULT 0,
    grid_charged_w              DECIMAL(10,3)   NOT NULL DEFAULT 0,
    decision_engine             VARCHAR(30)     NOT NULL,
    ml_confidence_score         DECIMAL(5,4)    NULL,

    -- Standard tariff context
    tariff_slot_name            VARCHAR(80)     NULL,
    tariff_price_per_kwh        DECIMAL(6,4)    NULL,
    was_grid_charge_favorable   TINYINT(1)      NOT NULL DEFAULT 0,
    solar_expected_soon         TINYINT(1)      NOT NULL DEFAULT 0,
    hours_to_next_favorable_tariff DECIMAL(5,2) NULL,
    avg_solar_forecast_wm2      DECIMAL(7,2)    NULL,
    tariff_max_savings_per_kwh  DECIMAL(6,4)    NULL,

    -- ML-7: adaptive context (extended)
    hours_remaining_in_slot     DECIMAL(5,2)    NULL    COMMENT 'Hours remaining in the off-peak tariff slot',
    hours_until_solar           DECIMAL(5,2)    NULL    COMMENT 'Hours until solar generation (null = not forecast)',
    had_emergency_grid_charge   TINYINT(1)      NOT NULL DEFAULT 0 COMMENT 'At least one battery had an emergency grid charge',
    effective_grid_charge_w     DECIMAL(8,2)    NULL    COMMENT 'Adaptive average grid charge power outside emergencies (W)',

    -- ML-8: Home Assistant (HA) site-specific forecasts
    forecast_today_wh           DECIMAL(10,2)   NULL    COMMENT 'Estimated solar production today from Home Assistant (Wh)',
    forecast_tomorrow_wh        DECIMAL(10,2)   NULL    COMMENT 'Estimated solar production tomorrow from Home Assistant (Wh)',

    -- v4: Load Forecasting
    measured_consumption_w              DECIMAL(10,2) NULL COMMENT 'Measured home consumption during the cycle (W)',
    estimated_consumption_next_hours_wh DECIMAL(10,2) NULL COMMENT 'Estimated consumption for the next hours (Wh) — rolling avg × horizon',

    -- v5: Intraday Solcast + Daily balance
    forecast_remaining_today_wh DECIMAL(10,2) NULL COMMENT 'Remaining solar today from Solcast (Wh)',
    energy_deficit_today_wh     DECIMAL(10,2) NULL COMMENT 'Daily energy deficit (Wh): requirement − remaining_solar. Negative = solar sufficient',
    daily_solar_consumed_wh     DECIMAL(10,2) NULL COMMENT 'Solar self-consumed since midnight (Wh): forecast_today_start − forecast_remaining_now',

    PRIMARY KEY (id),
    INDEX idx_session_requested_at  (requested_at),
    INDEX idx_session_engine        (decision_engine),
    INDEX idx_session_tariff        (tariff_slot_name),
    INDEX idx_session_has_forecast  (forecast_today_wh, forecast_tomorrow_wh),
    INDEX idx_session_energy_balance (energy_deficit_today_wh, forecast_remaining_today_wh, daily_solar_consumed_wh)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── battery_snapshots ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS battery_snapshots (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    session_id                  BIGINT          NOT NULL,
    battery_id                  INT             NOT NULL,
    capacity_wh                 DECIMAL(10,2)   NOT NULL DEFAULT 0,
    max_charge_rate_w           DECIMAL(8,2)    NOT NULL DEFAULT 0,
    min_percent                 DECIMAL(5,2)    NOT NULL DEFAULT 0,
    soft_max_percent            DECIMAL(5,2)    NOT NULL DEFAULT 80,
    current_percent_before      DECIMAL(5,2)    NOT NULL DEFAULT 0,
    current_percent_after       DECIMAL(5,2)    NOT NULL DEFAULT 0,
    priority                    INT             NOT NULL DEFAULT 0,
    was_urgent                  TINYINT(1)      NOT NULL DEFAULT 0,
    allocated_w                 DECIMAL(8,2)    NOT NULL DEFAULT 0,
    is_grid_charge              TINYINT(1)      NOT NULL DEFAULT 0,
    -- ML-7: per-battery emergency context
    is_emergency_grid_charge    TINYINT(1)      NOT NULL DEFAULT 0 COMMENT 'Emergency grid charge due to critical SOC',
    grid_charge_allowed_w       DECIMAL(8,2)    NOT NULL DEFAULT 0 COMMENT 'Adaptive allowed grid charge power (W)',
    reason                      VARCHAR(300)    NOT NULL DEFAULT '',
    -- ML-8: battery lifecycle
    cycle_count                 INT             NOT NULL DEFAULT 0 COMMENT 'Number of charge cycles for this battery at session time',

    PRIMARY KEY (id),
    INDEX idx_snapshot_session_battery (session_id, battery_id),
    CONSTRAINT fk_snapshot_session
        FOREIGN KEY (session_id) REFERENCES distribution_sessions(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── weather_snapshots ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS weather_snapshots (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    session_id                  BIGINT          NOT NULL UNIQUE,
    fetched_at                  DATETIME(6)     NOT NULL,
    latitude                    DOUBLE          NOT NULL DEFAULT 0,
    longitude                   DOUBLE          NOT NULL DEFAULT 0,
    temperature_c               DECIMAL(5,2)    NOT NULL DEFAULT 0,
    cloud_cover_percent         DECIMAL(5,2)    NOT NULL DEFAULT 0,
    precipitation_mm_h          DECIMAL(6,3)    NOT NULL DEFAULT 0,
    direct_radiation_wm2        DECIMAL(7,2)    NOT NULL DEFAULT 0,
    diffuse_radiation_wm2       DECIMAL(7,2)    NOT NULL DEFAULT 0,
    daylight_hours              DECIMAL(4,2)    NOT NULL DEFAULT 0,
    hours_until_sunset          DECIMAL(4,2)    NOT NULL DEFAULT 0,
    radiation_forecast_12h_json VARCHAR(1000)   NOT NULL DEFAULT '[]',
    cloud_forecast_12h_json     VARCHAR(500)    NOT NULL DEFAULT '[]',

    PRIMARY KEY (id),
    CONSTRAINT fk_weather_session
        FOREIGN KEY (session_id) REFERENCES distribution_sessions(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── ml_prediction_logs ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ml_prediction_logs (
    id                              BIGINT          NOT NULL AUTO_INCREMENT,
    session_id                      BIGINT          NOT NULL UNIQUE,
    model_version                   VARCHAR(30)     NOT NULL,
    confidence_score                DECIMAL(5,4)    NOT NULL DEFAULT 0,
    efficiency_score                DECIMAL(5,4)    NOT NULL DEFAULT 0,
    predicted_soft_max_json         VARCHAR(200)    NOT NULL DEFAULT '',
    predicted_preventive_threshold  DECIMAL(5,2)    NOT NULL DEFAULT 0,
    was_applied                     TINYINT(1)      NOT NULL DEFAULT 0,
    predicted_at                    DATETIME(6)     NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_mllog_session
        FOREIGN KEY (session_id) REFERENCES distribution_sessions(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── session_feedbacks ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_feedbacks (
    id                          BIGINT          NOT NULL AUTO_INCREMENT,
    session_id                  BIGINT          NOT NULL UNIQUE,
    collected_at                DATETIME(6)     NOT NULL,
    feedback_delay_hours        DOUBLE          NOT NULL DEFAULT 0,
    observed_soc_json           VARCHAR(500)    NOT NULL DEFAULT '{}',
    avg_soc_at_feedback         DOUBLE          NOT NULL DEFAULT 0,
    min_soc_at_feedback         DOUBLE          NOT NULL DEFAULT 0,
    energy_efficiency_score     DECIMAL(5,4)    NOT NULL DEFAULT 0,
    availability_score          DECIMAL(5,4)    NOT NULL DEFAULT 0,
    observed_optimal_soft_max   DECIMAL(5,2)    NOT NULL DEFAULT 80,
    observed_optimal_preventive DECIMAL(5,2)    NOT NULL DEFAULT 20,
    composite_score             DECIMAL(5,4)    NOT NULL DEFAULT 0,
    -- ML-7: additional labels and metrics
    actual_self_sufficiency_pct DECIMAL(6,3)  NULL    COMMENT 'Actual self-sufficiency rate 0-1 measured after the session',
    did_import_from_grid        TINYINT(1)    NULL    COMMENT '1 if a significant grid import was detected after the session',
    should_charge_from_grid     TINYINT(1)    NULL    COMMENT 'ML-7c label: 1 if the session should have charged from the grid',
    surplus_wasted              TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '1 if solar surplus was wasted (batteries full)',
    training_weight             DECIMAL(5,3)  NOT NULL DEFAULT 1.0 COMMENT 'ML training weight, >1 for problematic sessions',
    status                      TINYINT         NOT NULL DEFAULT 0
                                COMMENT '0=Pending 1=Valid 2=Invalid 3=Skipped',
    invalid_reason              VARCHAR(200)    NULL,

    PRIMARY KEY (id),
    INDEX idx_feedback_status    (status),
    INDEX idx_feedback_collected (collected_at),
    INDEX idx_sf_should_charge   (should_charge_from_grid),
    CONSTRAINT fk_feedback_session
        FOREIGN KEY (session_id) REFERENCES distribution_sessions(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── daily_summaries (migration_daily_summary.sql) ───────────────────────────
CREATE TABLE IF NOT EXISTS daily_summaries (
    id                      BIGINT          NOT NULL AUTO_INCREMENT,
    date                    DATE            NOT NULL,
    solar_consumed_wh       DECIMAL(12,2)   NULL    COMMENT 'Solar energy self-consumed since midnight (Wh)',
    grid_consumed_wh        DECIMAL(12,2)   NOT NULL DEFAULT 0 COMMENT 'Total grid energy consumed during the day (Wh)',
    grid_charged_wh         DECIMAL(12,2)   NOT NULL DEFAULT 0 COMMENT 'Grid energy → batteries (Wh)',
    solar_allocated_wh      DECIMAL(12,2)   NOT NULL DEFAULT 0 COMMENT 'Surplus solar energy → batteries (Wh)',
    unused_surplus_wh       DECIMAL(12,2)   NOT NULL DEFAULT 0 COMMENT 'Undistributed solar surplus (Wh)',
    estimated_savings_eur   DECIMAL(8,4)    NULL    COMMENT 'Estimated savings (€)',
    self_sufficiency_pct    DECIMAL(5,2)    NULL    COMMENT 'Self-sufficiency rate (%)',
    session_count           INT             NOT NULL DEFAULT 0 COMMENT 'Number of distribution sessions on this day',
    computed_at             DATETIME(6)     NOT NULL COMMENT 'UTC timestamp of the last calculation/recalculation',

    PRIMARY KEY (id),
    UNIQUE KEY uq_daily_summary_date (date),
    INDEX idx_daily_summary_date (date),
    INDEX idx_daily_summary_self_sufficiency (date, self_sufficiency_pct)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Aggregated daily energy summary. One row per calendar date (UTC).';

-- ── Views / derived utilities (migration v6)
CREATE OR REPLACE VIEW battery_lifecycle_summary AS
SELECT
    bs.battery_id,
    MAX(bs.cycle_count)                          AS latest_cycle_count,
    MAX(ds.requested_at)                         AS last_seen_at,
    COUNT(*)                                     AS total_sessions,
    AVG(bs.current_percent_before)               AS avg_soc_at_session,
    SUM(CASE WHEN bs.is_emergency_grid_charge = 1 THEN 1 ELSE 0 END) AS emergency_sessions
FROM battery_snapshots bs
JOIN distribution_sessions ds ON ds.id = bs.session_id
WHERE bs.cycle_count > 0
GROUP BY bs.battery_id;