using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Diagnostics.HealthChecks;  // Fix CS1061 : AddDbContextCheck
using Microsoft.OpenApi.Models;
using SolarDistribution.Core.Services;
using SolarDistribution.Core.Services.ML;
using SolarDistribution.Infrastructure.Data;
using SolarDistribution.Infrastructure.Repositories;
using SolarDistribution.Core.Repositories;
using SolarDistribution.Infrastructure.Services;
using SolarDistribution.Infrastructure.Mapping;

var builder = WebApplication.CreateBuilder(args);

// ── Controllers ───────────────────────────────────────────────────────────────
builder.Services.AddControllers();

// ── MariaDB / EF Core ─────────────────────────────────────────────────────────
var connectionString = builder.Configuration.GetConnectionString("MariaDb")
    ?? throw new InvalidOperationException("Connection string 'MariaDb' not found.");

builder.Services.AddDbContext<SolarDbContext>(options =>
    options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString),
        mysql => mysql.EnableRetryOnFailure(3)));

// ── Repositories ──────────────────────────────────────────────────────────────
builder.Services.AddScoped<IDistributionRepository, DistributionRepository>();

// ── Core services ─────────────────────────────────────────────────────────────
builder.Services.AddSingleton<IBatteryDistributionService, BatteryDistributionService>();
builder.Services.AddScoped<SmartDistributionService>();
// Fix #6 : factory de sessions (mapping métier → entités EF)
builder.Services.AddScoped<IDistributionSessionFactory, DistributionSessionFactory>();
// TariffEngine — inject an empty TariffConfig by default (API standalone without config.yaml).
// In production the Worker injects the real config loaded from config.yaml.
builder.Services.AddSingleton<TariffEngine>(sp => new TariffEngine(new TariffConfig()));

// ── ML.NET ────────────────────────────────────────────────────────────────────
// Register ML service as scoped because it depends on a scoped repository.
builder.Services.AddScoped<IDistributionMLService>(sp =>
{
    var repo     = sp.GetRequiredService<IDistributionRepository>();
    var logger   = sp.GetRequiredService<ILogger<DistributionMLService>>();
    var modelDir = builder.Configuration["ML:ModelDirectory"] ?? "ml_models";
    return new DistributionMLService(repo, logger, modelDir);
});

// ── Open-Meteo weather service ─────────────────────────────────────────────────
builder.Services.AddHttpClient<IWeatherService, OpenMeteoWeatherService>(client =>
{
    client.Timeout = TimeSpan.FromSeconds(10);
    client.DefaultRequestHeaders.Add("User-Agent", "SolarDistribution/1.0");
});

// ── Swagger ───────────────────────────────────────────────────────────────────
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title       = "Solar Distribution API",
        Version     = "v1",
        Description = """
            Intelligently distributes solar surplus to batteries.

            **Decision engines:**
            - `Deterministic` — priority/proportional algorithm (always available)
            - `ML` — ML.NET model (active after 50 sessions, R² ≥ 0.65)
            - `ML-Fallback` — ML active but partially confident

            **Persisted data** (MariaDB): each `/calculate` call stores
            the session, battery states, Open-Meteo weather and ML log.

            **Retrain**: `POST /api/ml/retrain` — manual, on demand.
            """,
        Contact = new OpenApiContact
        {
            Name = "SolarDistribution",
            Url  = new Uri("https://github.com/your-org/SolarDistribution")
        }
    });

    // ── XML comments (generated by <GenerateDocumentationFile>true</GenerateDocumentationFile>)
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
        options.IncludeXmlComments(xmlPath);

    // ── API Key security (optional — activated via Swagger:ApiKey:Enabled = true)
    // Allows protecting Swagger in production with a simple header key.
    bool apiKeyEnabled = builder.Configuration.GetValue<bool>("Swagger:ApiKey:Enabled");
    if (apiKeyEnabled)
    {
        options.AddSecurityDefinition("ApiKey", new OpenApiSecurityScheme
        {
            Name        = "X-Api-Key",
            Type        = SecuritySchemeType.ApiKey,
            In          = ParameterLocation.Header,
            Description = "API Key — add header: X-Api-Key: <your-key>"
        });
        options.AddSecurityRequirement(new OpenApiSecurityRequirement
        {
            {
                new OpenApiSecurityScheme
                {
                    Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "ApiKey" }
                },
                Array.Empty<string>()
            }
        });
    }
});

// ── CORS — Fix #3 : configurable via appsettings.json ────────────────────────
// Dev  : Cors:AllowAnyOrigin = true  → tous les origines autorisés (pratique local)
// Prod : Cors:AllowAnyOrigin = false → uniquement les origines listées dans Cors:AllowedOrigins
builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy =>
    {
        bool allowAny = builder.Configuration.GetValue<bool>("Cors:AllowAnyOrigin");

        if (allowAny)
        {
            policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod();
        }
        else
        {
            var origins = builder.Configuration
                .GetSection("Cors:AllowedOrigins")
                .Get<string[]>() ?? Array.Empty<string>();

            policy.WithOrigins(origins)
                  .AllowAnyHeader()
                  .AllowAnyMethod();
        }
    }));

// ── Health Checks — Fix #7 ────────────────────────────────────────────────────
// Expose /health (liveness) et /health/ready (readiness + DB check)
builder.Services.AddHealthChecks()
    .AddDbContextCheck<SolarDbContext>("mariadb");

// ── Build ─────────────────────────────────────────────────────────────────────
var app = builder.Build();

// Migration automatique au démarrage (dev uniquement — utiliser le script SQL en prod)
if (app.Environment.IsDevelopment())
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<SolarDbContext>();
    await db.Database.MigrateAsync();
}

// ── Swagger — available in all environments ───────────────────────────────────
// Use Swagger:RoutePrefix in appsettings to customise the UI path (default: "swagger")
// Set Swagger:Enabled = false in appsettings.json to completely disable in production
bool swaggerEnabled = builder.Configuration.GetValue<bool>("Swagger:Enabled", defaultValue: true);

if (swaggerEnabled)
{
    app.UseSwagger();

    var routePrefix  = builder.Configuration.GetValue<string>("Swagger:RoutePrefix") ?? "swagger";
    var swaggerTitle = builder.Configuration.GetValue<string>("Swagger:Title") ?? "Solar Distribution API v1";

    // ── API Key guard — protège l'accès à l'UI et au JSON Swagger
    bool apiKeyEnabled = builder.Configuration.GetValue<bool>("Swagger:ApiKey:Enabled");
    if (apiKeyEnabled)
    {
        var expectedKey = builder.Configuration.GetValue<string>("Swagger:ApiKey:Key")
            ?? throw new InvalidOperationException("Swagger:ApiKey:Key must be set when Swagger:ApiKey:Enabled = true.");

        app.Use(async (context, next) =>
        {
            // Applique le guard uniquement sur les routes Swagger
            var path = context.Request.Path.Value ?? "";
            bool isSwaggerPath = path.StartsWith("/swagger", StringComparison.OrdinalIgnoreCase);

            if (isSwaggerPath)
            {
                if (!context.Request.Headers.TryGetValue("X-Api-Key", out var providedKey)
                    || providedKey != expectedKey)
                {
                    context.Response.StatusCode  = StatusCodes.Status401Unauthorized;
                    context.Response.ContentType = "application/json";
                    await context.Response.WriteAsync("{\"error\":\"Missing or invalid X-Api-Key header.\"}");
                    return;
                }
            }

            await next();
        });
    }

    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", swaggerTitle);
        // routePrefix = "" → Swagger at root "/"
        // routePrefix = "swagger" → Swagger at "/swagger"
        c.RoutePrefix = routePrefix == "/" ? string.Empty : routePrefix;

        // UX improvements
        c.DisplayRequestDuration();
        c.EnableDeepLinking();
        c.EnableFilter();
        c.DefaultModelsExpandDepth(2);
    });
}

app.UseCors();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

// Fix #7 : endpoints health check
app.MapHealthChecks("/health");

app.Run();

public partial class Program { }
